In [2]:
import numpy as np
import pandas as pd

In [3]:
# Carga de archivos
demograficos = pd.read_csv('./DM_DatosGenerales.txt', delimiter='|', encoding='latin1', header=0, dtype=object)
dispersiones = pd.read_csv('./DM_DatosDispersion.txt', delimiter='|', encoding='latin1', header=0, dtype=object)
domicilios = pd.read_csv('./DM_DatosDomicilio.txt', delimiter='|', encoding='latin1', header=0, dtype=object)
marca_big = pd.read_csv('./Marca_BIG.txt', delimiter='|', encoding='latin1', header=0, dtype=object)

In [4]:
demograficos

,#FI_ID_INSTITUCION,FI_EMPLEADO,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FC_INSTITUCION,FC_NOMBRECOMPLETO,FD_FECHANACIMIENTO,FC_PAISNACIMIENTO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
0,4673,236644,1,1,4003,13916,IMSS PENSIONADOS,GUILLERMO DAGOBERTO NAVA GONZALEZ,11/01/1921 00:00:00,MEXICO,...,NAVA,GONZALEZ,1,09/14/2007 00:00:00,1,19,2,7,2,484
1,4673,236645,1,1,2749,33898,IMSS PENSIONADOS,GUILLERMO FEDERICO MARTINEZ CABRERA,07/21/1945 00:00:00,MEXICO,...,MARTINEZ,CABRERA,1,03/28/2018 00:00:00,1,28,4,7,2,484
2,4673,236648,1,1,3654,34850,IMSS PENSIONADOS,GUILLERMO HECTOR SOTO CABAÑAS,06/25/1944 00:00:00,MEXICO,...,SOTO,CABAÑAS,1,05/19/2012 00:00:00,1,15,2,7,2,484
3,4673,236656,1,1,2781,33562,IMSS PENSIONADOS,HECTOR JOSE GUZMAN GUTIERREZ,12/18/1949 00:00:00,MEXICO,...,GUZMAN,GUTIERREZ,1,06/13/2011 00:00:00,1,14,2,7,2,484
4,4673,236659,1,1,5128,18979,IMSS PENSIONADOS,HECTOR JULIO NAVARRO GUTIERREZ,07/14/1944 00:00:00,MEXICO,...,NAVARRO,GUTIERREZ,1,05/15/2007 00:00:00,1,26,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2223545,6626,2163353,1,1,5306,4881,INTIMARK S DE R L DE C V,MACARIO HERMENEGILDO SEGUNDO,04/25/1975 00:00:00,NaN,...,HERMENEGILDO,SEGUNDO,1,NaN,1,15,0,7,2,484
2223546,5383,2130648,1,1,6729,103016,BAZ PORTABILIDAD NOMINA,RAQUEL MENDIOLA GALINDO,08/01/1961 00:00:00,NaN,...,MENDIOLA,GALINDO,1,02/15/2021 17:48:58,1,11,1,7,1,484
2223547,5383,2156178,1,9,8681,15624,BAZ PORTABILIDAD NOMINA,LUIS IGNACIO ZUMAYA MERAZ,10/19/2001 00:00:00,NaN,...,ZUMAYA,MERAZ,1,02/25/2021 17:58:32,1,24,0,7,2,484
2223548,5383,2132523,1,39,4727,2946,BAZ PORTABILIDAD NOMINA,JOSE CRISANTOS SOTO CASAS,05/26/1994 00:00:00,NaN,...,SOTO,CASAS,1,02/17/2021 17:04:40,1,14,0,7,2,484
2223549,5983,2158180,1,1,6774,72966,LIDERES EN INNOVACION SA DE CV,MIGUEL ANGEL NAVA CABELLO,07/19/1997 00:00:00,NaN,...,NAVA,CABELLO,1,NaN,1,17,2,7,2,484

In [5]:
dispersiones['FN_SALARIO'] = dispersiones['FN_SALARIO'].astype(float)

In [6]:
dispersiones['FIPERIODICIDADPAGO'] = pd.to_numeric(dispersiones['FIPERIODICIDADPAGO'], errors='coerce')

In [7]:
dispersiones = dispersiones.dropna(subset=['FIPERIODICIDADPAGO'])

In [8]:
dispersiones = dispersiones.dropna(subset=['FI_TOTALDISPER'])

In [9]:
dispersiones['FIPERIODICIDADPAGO'] = dispersiones['FIPERIODICIDADPAGO'].astype(int)

In [10]:
dispersiones['FI_TOTALDISPER'] = dispersiones['FI_TOTALDISPER'].astype(int)

In [11]:
dispersiones = dispersiones[dispersiones['FN_SALARIO'] > 0]

In [12]:
dispersiones['FIPERIODICIDADPAGO'] = dispersiones['FIPERIODICIDADPAGO'].astype(int)

In [13]:
dispersiones

,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_CUENTA,FD_ULTIMADISPER,FI_TOTALDISPER,FN_SALARIO,FC_PERIODICIDADPAGO,FI_CAPACIDADPAGO,FC_PRODUCTO,FI_ID_PRODUCTO,FI_CREDITOSACTIV,FIPERIODICIDADPAGO,FI_CTA_DIGITOS
2,4673,242209,01272132910106618084,11/30/2021 00:00:00,7,19099.48,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,106618084
5,4673,242244,01271850800109297939,11/30/2021 00:00:00,7,9738.18,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,2,3,109297939
7,4673,242257,01275002930180288218,11/30/2021 00:00:00,7,2324.67,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,180288218
8,4673,242258,01270518230186223129,11/30/2021 00:00:00,7,2982.38,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,186223129
11,4673,242267,01270185550110359915,11/30/2021 00:00:00,7,7668.34,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,110359915
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2226012,5383,2770286,01274297230161104028,12/14/2021 00:00:00,13,2913.41,QUINCENAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,0,2,161104028
2226013,5383,2681052,01270148160159598051,12/13/2021 00:00:00,18,472.08,SEMANAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,0,1,159598051
2226015,4673,2755816,01276318600126183128,11/30/2021 00:00:00,4,5780.85,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,126183128
2226016,4673,2756309,01272396861376542099,11/30/2021 00:00:00,4,5581.51,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,1376542099
2226017,5383,2765944,01276923210161006636,12/10/2021 00:00:00,14,1293.96,SEMANAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,1,1,161006636

In [14]:
empleados_muestra = dispersiones.sample(n=100000)

In [15]:
domicilios = domicilios.dropna(subset=['FC_LATITUD'])

In [16]:
domicilios = domicilios.dropna(subset=['FC_ID_ESTADO'])

In [17]:
domicilios = domicilios.dropna(subset=['FI_ID_MUNICIPIO'])

In [18]:
domicilios

,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_CALLEHOGAR,FC_NUMEXTHOGAR,FC_NUMINTHOGAR,FC_COLONIAHOGAR,FC_MUNICIPIOHOGAR,FC_ESTADOHOGAR,FC_CODIGOPOSTAL,FC_PAIS,FI_ID_TIPOVIVIENDA,FC_ID_TIPOVIVIENDA,FC_LATITUD,FC_LONGITUD,FC_SUCURSAL,FI_ID_COLONIA,FI_ID_MUNICIPIO,FC_ID_ESTADO,FI_ID_PAIS
0,4673,241071,CAMINO AL CAMPO,SN,SN,AMPLIACION PLAN DE AYALA,CUAUTLA,MORELOS,62740,MEXICO,3,PROPIA,18.7917820000000000,-98.9010970000000000,NaN,NaN,6,17,1
1,4673,235656,ESMERALDA,110,NaN,CUAUHTEMOC,SAN NICOLAS DE LOS GARZA,NUEVO LEON,66450,MEXICO,3,PROPIA,25.7328120000000000,-100.2946250000000000,NaN,2,46,19,1
2,4673,235657,SANTIAGO DEL ESTE,305,305,VILLAS DEL SUR,QUERETARO,QUERETARO,76148,MEXICO,3,PROPIA,20.6549980000000000,-100.3938090000000000,NaN,NaN,14,22,1
3,4673,235658,GUADALUPE VICTORIA,1,1,TEOCELO,TEOCELO,VERACRUZ,91615,MEXICO,3,PROPIA,19.3860900000000000,-96.9746210000000000,NaN,1,164,30,1
4,4673,235659,HUAMAC,8017,8017,LOMAS DE CUMBRES,MONTERREY,NUEVO LEON,64140,MEXICO,3,PROPIA,25.7375740000000000,-100.3584220000000000,NaN,NaN,39,19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2223368,11055,2764501,C SIN NOMBRE S/N,00000,NaN,Centro Cruz de Elota Sinaloa,ELOTA,SINALOA,82700,MEXICO,3,PROPIA,23.9317920000000000,-106.8830300000000000,NaN,NaN,8,25,1
2223369,5383,2752786,AV ALVARO OBREGON,3,NaN,Vicente Guerrero,Delicias,CHIHUAHUA,33100,MEXICO,3,PROPIA,28.1982830000000000,-105.4286970000000000,NaN,NaN,21,8,1
2223370,5383,2775670,SANTA ROSALA,1135,NaN,SANTA MARIA,GUADALAJARA,JALISCO,44350,Mexico,3,PROPIA,20.6873130000000000,-103.3135330000000000,NaN,5,39,14,1
2223371,4673,2756257,NARDO,104,NaN,SANTA JULIA AMPLIACION,PACHUCA DE SOTO,HIDALGO,42080,Mexico,3,PROPIA,20.1105960000000000,-98.7668020000000000,NaN,10,48,13,1
2223377,5383,2681182,PRIV LOTUS 10,10,NaN,El Cerrito,Huauchinango,PUEBLA,73160,MEXICO,3,PROPIA,20.1555560000000000,-98.0343770000000000,NaN,25,71,21,1

In [19]:
domicilios = domicilios.dropna(subset=['FI_ID_COLONIA'])

In [20]:
domicilios

,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_CALLEHOGAR,FC_NUMEXTHOGAR,FC_NUMINTHOGAR,FC_COLONIAHOGAR,FC_MUNICIPIOHOGAR,FC_ESTADOHOGAR,FC_CODIGOPOSTAL,FC_PAIS,FI_ID_TIPOVIVIENDA,FC_ID_TIPOVIVIENDA,FC_LATITUD,FC_LONGITUD,FC_SUCURSAL,FI_ID_COLONIA,FI_ID_MUNICIPIO,FC_ID_ESTADO,FI_ID_PAIS
1,4673,235656,ESMERALDA,110,NaN,CUAUHTEMOC,SAN NICOLAS DE LOS GARZA,NUEVO LEON,66450,MEXICO,3,PROPIA,25.7328120000000000,-100.2946250000000000,NaN,2,46,19,1
3,4673,235658,GUADALUPE VICTORIA,1,1,TEOCELO,TEOCELO,VERACRUZ,91615,MEXICO,3,PROPIA,19.3860900000000000,-96.9746210000000000,NaN,1,164,30,1
7,4673,235665,64 X 41 Y 43,365B,365B,MERIDA CENTRO,MERIDA,YUCATAN,97000,MEXICO,3,PROPIA,20.9709650000000000,-89.6251680000000000,NaN,1,50,31,1
9,4673,235669,DR BALMIS,24,24,DOCTORES,CUAUHTEMOC,DISTRITO FEDERAL,06720,MEXICO,3,PROPIA,19.4168930000000000,-99.1486160000000000,NaN,1,6,9,1
10,4673,242188,EX CAROLINA,SN,SN,CENTRO,COSAMALOAPAN,VERACRUZ,95400,MEXICO,3,PROPIA,18.3677680000000000,-95.7917570000000000,NaN,40,45,30,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2223365,11055,2764482,AD PROVENIR,9,9,FRACC. EL RETIRO,SANTA MARIA DEL TULE,OAXACA,68297,MEXICO,3,PROPIA,17.0500750000000000,-96.6265490000000000,NaN,4,409,20,1
2223366,11055,2764496,ROBERTO GARCIA BARRON,1946,NaN,ISSSTE SIN,AHOME,SINALOA,81215,MEXICO,3,PROPIA,25.8090870000000000,-108.9758730000000000,NaN,1,1,25,1
2223370,5383,2775670,SANTA ROSALA,1135,NaN,SANTA MARIA,GUADALAJARA,JALISCO,44350,Mexico,3,PROPIA,20.6873130000000000,-103.3135330000000000,NaN,5,39,14,1
2223371,4673,2756257,NARDO,104,NaN,SANTA JULIA AMPLIACION,PACHUCA DE SOTO,HIDALGO,42080,Mexico,3,PROPIA,20.1105960000000000,-98.7668020000000000,NaN,10,48,13,1
2223377,5383,2681182,PRIV LOTUS 10,10,NaN,El Cerrito,Huauchinango,PUEBLA,73160,MEXICO,3,PROPIA,20.1555560000000000,-98.0343770000000000,NaN,25,71,21,1

In [21]:
subset = dispersiones.merge(domicilios, on='FI_EMPLEADO')

In [22]:
test = dispersiones.merge(domicilios, on='FI_EMPLEADO').merge(demograficos, on='FI_EMPLEADO')

In [23]:
test = test.sample(n=1000)

In [24]:
test

,#FI_ID_INSTITUCION_x,FI_EMPLEADO,FC_CUENTA,FD_ULTIMADISPER,FI_TOTALDISPER,FN_SALARIO,FC_PERIODICIDADPAGO,FI_CAPACIDADPAGO,FC_PRODUCTO,FI_ID_PRODUCTO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS_y,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
25722,4673,254435,01278765750107254356,11/30/2021 00:00:00,7,2795.84,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,GARCIA,LOPEZ,1,03/28/2018 00:00:00,1,28,5,7,1,484
182346,11879,2464687,01274802600120925148,12/09/2021 00:00:00,18,4851.71,SEMANAL,NaN,NOMINA AZTECA,10,...,DIAZ,LEY,1,12/06/2020 00:00:00,1,28,2,7,1,484
24235,4673,261468,01278684360181466578,11/30/2021 00:00:00,7,3224.77,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,DE LA CRUZ,ISLENO,1,03/28/2018 00:00:00,1,30,2,7,2,484
93552,4673,1530516,01270602181342037346,11/30/2021 00:00:00,7,4724.67,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,NaN,RAMIREZ,1,NaN,1,11,3,7,2,484
208417,4673,2684580,01279740110141696900,11/30/2021 00:00:00,5,15370.32,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,INFANTE,MATA,1,12/08/2020 00:00:00,1,24,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,01272196061318642100,11/30/2021 00:00:00,7,32709.01,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,DIAZ,HERNANDEZ,1,NaN,1,20,3,7,2,484
86232,5383,1391944,01275116860132501362,11/30/2021 00:00:00,8,5652.40,MENSUAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,...,FISHER,MELGAR,1,03/11/2020 16:58:21,1,3,0,7,1,484
171619,5383,2347521,01273278040152027698,11/16/2021 00:00:00,6,4310.00,MENSUAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,...,CARRILLO,AMAYA,1,12/05/2020 00:00:00,1,31,1,7,2,484
32713,4673,311643,01272080250173879726,11/30/2021 00:00:00,7,3054.92,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,MARTINEZ,DOMINGUEZ,1,10/18/2016 00:00:00,1,9,2,7,2,484
15933,4673,197140,01272063110197317386,11/30/2021 00:00:00,7,2945.11,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,...,GARCIA,VALDEZ,1,12/28/2011 00:00:00,1,15,1,7,1,484

In [25]:
test.columns

Index(['#FI_ID_INSTITUCION_x', 'FI_EMPLEADO', 'FC_CUENTA', 'FD_ULTIMADISPER',
       'FI_TOTALDISPER', 'FN_SALARIO', 'FC_PERIODICIDADPAGO',
       'FI_CAPACIDADPAGO', 'FC_PRODUCTO', 'FI_ID_PRODUCTO', 'FI_CREDITOSACTIV',
       'FIPERIODICIDADPAGO', 'FI_CTA_DIGITOS', '#FI_ID_INSTITUCION_y',
       'FC_CALLEHOGAR', 'FC_NUMEXTHOGAR', 'FC_NUMINTHOGAR', 'FC_COLONIAHOGAR',
       'FC_MUNICIPIOHOGAR', 'FC_ESTADOHOGAR', 'FC_CODIGOPOSTAL', 'FC_PAIS',
       'FI_ID_TIPOVIVIENDA', 'FC_ID_TIPOVIVIENDA', 'FC_LATITUD', 'FC_LONGITUD',
       'FC_SUCURSAL', 'FI_ID_COLONIA', 'FI_ID_MUNICIPIO', 'FC_ID_ESTADO',
       'FI_ID_PAIS_x', '#FI_ID_INSTITUCION', 'FI_PAISCU', 'FI_CANALCU',
       'FI_SUCURSALCU', 'FI_FOLIOCU', 'FC_INSTITUCION', 'FC_NOMBRECOMPLETO',
       'FD_FECHANACIMIENTO', 'FC_PAISNACIMIENTO', 'FC_ESTADONACIMIENTO',
       'FI_EDAD', 'FC_RFC', 'FC_CURP', 'FC_NSS', 'FC_ESTADOCIVIL',
       'FC_ESCOLARIDAD', 'FC_SEXO', 'FC_TELEFONOCASA', 'FC_TELCELULAR',
       'FC_EMAIL', 'FC_AVISOPRIVACIDAD', 'FC_CONSULTABURO',
       'FC_USODATOSPERSONA', 'FC_USODATOSPROMO', 'FC_NACIONALIDAD',
       'FD_ALTAEMPLEADO', 'FI_DATOS_CORRECTOS', 'FI_OFERTA', 'FC_STATUS_EMP',
       'FI_STATUS_EMP', 'FC_NOMBRE_EMPLEADO', 'FC_APELLIDO_PATERNO',
       'FC_APELLIDO_MATERNO', 'FI_ID_PAIS_y', 'FD_FECHA_ALTA',
       'FNPAISNACIMIENTO', 'FNEDONACIMIENTO', 'FNESTADOCIVIL', 'FNESCOLARIDAD',
       'FNSEXO', 'FNNACIONALIDAD'],
      dtype='object')

In [26]:
m_demograficos = test[['#FI_ID_INSTITUCION', 'FI_EMPLEADO', 'FI_PAISCU', 'FI_CANALCU',
       'FI_SUCURSALCU', 'FI_FOLIOCU', 'FC_INSTITUCION', 'FC_NOMBRECOMPLETO',
       'FD_FECHANACIMIENTO', 'FC_PAISNACIMIENTO', 'FC_ESTADONACIMIENTO',
       'FI_EDAD', 'FC_RFC', 'FC_CURP', 'FC_NSS', 'FC_ESTADOCIVIL',
       'FC_ESCOLARIDAD', 'FC_SEXO', 'FC_TELEFONOCASA', 'FC_TELCELULAR',
       'FC_EMAIL', 'FC_AVISOPRIVACIDAD', 'FC_CONSULTABURO',
       'FC_USODATOSPERSONA', 'FC_USODATOSPROMO', 'FC_NACIONALIDAD',
       'FD_ALTAEMPLEADO', 'FI_DATOS_CORRECTOS', 'FI_OFERTA', 'FC_STATUS_EMP',
       'FI_STATUS_EMP', 'FC_NOMBRE_EMPLEADO', 'FC_APELLIDO_PATERNO',
       'FC_APELLIDO_MATERNO', 'FI_ID_PAIS_y', 'FD_FECHA_ALTA',
       'FNPAISNACIMIENTO', 'FNEDONACIMIENTO', 'FNESTADOCIVIL', 'FNESCOLARIDAD',
       'FNSEXO', 'FNNACIONALIDAD']]

In [27]:
m_demograficos

,#FI_ID_INSTITUCION,FI_EMPLEADO,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FC_INSTITUCION,FC_NOMBRECOMPLETO,FD_FECHANACIMIENTO,FC_PAISNACIMIENTO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS_y,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
25722,4673,254435,1,1,8765,71946,IMSS PENSIONADOS,MARIA MONCERRATO GARCIA LOPEZ,10/27/1938 00:00:00,MEXICO,...,GARCIA,LOPEZ,1,03/28/2018 00:00:00,1,28,5,7,1,484
182346,11879,2464687,1,1,4802,41971,CUTSPEI SIN CLASIFICAR,ANA VELIA DIAZ LEY,12/03/1970 00:00:00,NaN,...,DIAZ,LEY,1,12/06/2020 00:00:00,1,28,2,7,1,484
24235,4673,261468,1,1,3638,32139,IMSS PENSIONADOS,PROCORO DE LA CRUZ ISLENO,04/09/1944 00:00:00,MEXICO,...,DE LA CRUZ,ISLENO,1,03/28/2018 00:00:00,1,30,2,7,2,484
93552,4673,1530516,1,1,602,65685,IMSS PENSIONADOS,MARCOS RAMIREZ,12/25/1945 00:00:00,NaN,...,NaN,RAMIREZ,1,NaN,1,11,3,7,2,484
208417,4673,2684580,1,1,9740,4858,IMSS PENSIONADOS,BERNABE INFANTE MATA,12/06/1960 00:00:00,NaN,...,INFANTE,MATA,1,12/08/2020 00:00:00,1,24,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,1,1,2196,3343,IMSS PENSIONADOS,LUIS JAVIER DIAZ HERNANDEZ,04/08/1960 00:00:00,NaN,...,DIAZ,HERNANDEZ,1,NaN,1,20,3,7,2,484
86232,5383,1391944,1,1,5116,27596,BAZ PORTABILIDAD NOMINA,GUADALUPE CONCEPCION FISHER MELGAR,09/15/1965 00:00:00,NaN,...,FISHER,MELGAR,1,03/11/2020 16:58:21,1,3,0,7,1,484
171619,5383,2347521,1,9,3278,7175,BAZ PORTABILIDAD NOMINA,RICARDO ALONSO CARRILLO AMAYA,12/08/1991 00:00:00,NaN,...,CARRILLO,AMAYA,1,12/05/2020 00:00:00,1,31,1,7,2,484
32713,4673,311643,1,20,9259,5969,IMSS PENSIONADOS,RODOLFO MARTINEZ DOMINGUEZ,09/27/1936 12:00:00,NaN,...,MARTINEZ,DOMINGUEZ,1,10/18/2016 00:00:00,1,9,2,7,2,484
15933,4673,197140,1,1,2063,41524,IMSS PENSIONADOS,ELENA GARCIA VALDEZ,02/03/1942 00:00:00,MEXICO,...,GARCIA,VALDEZ,1,12/28/2011 00:00:00,1,15,1,7,1,484

In [28]:
m_dispersiones = test[['#FI_ID_INSTITUCION_x', 'FI_EMPLEADO', 'FC_CUENTA', 'FD_ULTIMADISPER',
       'FI_TOTALDISPER', 'FN_SALARIO', 'FC_PERIODICIDADPAGO',
       'FI_CAPACIDADPAGO', 'FC_PRODUCTO', 'FI_ID_PRODUCTO', 'FI_CREDITOSACTIV',
       'FIPERIODICIDADPAGO', 'FI_CTA_DIGITOS']]

In [29]:
m_dispersiones

,#FI_ID_INSTITUCION_x,FI_EMPLEADO,FC_CUENTA,FD_ULTIMADISPER,FI_TOTALDISPER,FN_SALARIO,FC_PERIODICIDADPAGO,FI_CAPACIDADPAGO,FC_PRODUCTO,FI_ID_PRODUCTO,FI_CREDITOSACTIV,FIPERIODICIDADPAGO,FI_CTA_DIGITOS
25722,4673,254435,01278765750107254356,11/30/2021 00:00:00,7,2795.84,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,107254356
182346,11879,2464687,01274802600120925148,12/09/2021 00:00:00,18,4851.71,SEMANAL,NaN,NOMINA AZTECA,10,0,1,120925148
24235,4673,261468,01278684360181466578,11/30/2021 00:00:00,7,3224.77,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,181466578
93552,4673,1530516,01270602181342037346,11/30/2021 00:00:00,7,4724.67,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,1,3,1342037346
208417,4673,2684580,01279740110141696900,11/30/2021 00:00:00,5,15370.32,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,141696900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,01272196061318642100,11/30/2021 00:00:00,7,32709.01,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,1318642100
86232,5383,1391944,01275116860132501362,11/30/2021 00:00:00,8,5652.40,MENSUAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,0,3,132501362
171619,5383,2347521,01273278040152027698,11/16/2021 00:00:00,6,4310.00,MENSUAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,0,3,152027698
32713,4673,311643,01272080250173879726,11/30/2021 00:00:00,7,3054.92,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,173879726
15933,4673,197140,01272063110197317386,11/30/2021 00:00:00,7,2945.11,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,197317386

In [30]:
m_domicilios = test[['#FI_ID_INSTITUCION_y', 'FI_EMPLEADO',
       'FC_CALLEHOGAR', 'FC_NUMEXTHOGAR', 'FC_NUMINTHOGAR', 'FC_COLONIAHOGAR',
       'FC_MUNICIPIOHOGAR', 'FC_ESTADOHOGAR', 'FC_CODIGOPOSTAL', 'FC_PAIS',
       'FI_ID_TIPOVIVIENDA', 'FC_ID_TIPOVIVIENDA', 'FC_LATITUD', 'FC_LONGITUD',
       'FC_SUCURSAL', 'FI_ID_COLONIA', 'FI_ID_MUNICIPIO', 'FC_ID_ESTADO',
       'FI_ID_PAIS_x']]

In [31]:
m_demograficos.columns

Index(['#FI_ID_INSTITUCION', 'FI_EMPLEADO', 'FI_PAISCU', 'FI_CANALCU',
       'FI_SUCURSALCU', 'FI_FOLIOCU', 'FC_INSTITUCION', 'FC_NOMBRECOMPLETO',
       'FD_FECHANACIMIENTO', 'FC_PAISNACIMIENTO', 'FC_ESTADONACIMIENTO',
       'FI_EDAD', 'FC_RFC', 'FC_CURP', 'FC_NSS', 'FC_ESTADOCIVIL',
       'FC_ESCOLARIDAD', 'FC_SEXO', 'FC_TELEFONOCASA', 'FC_TELCELULAR',
       'FC_EMAIL', 'FC_AVISOPRIVACIDAD', 'FC_CONSULTABURO',
       'FC_USODATOSPERSONA', 'FC_USODATOSPROMO', 'FC_NACIONALIDAD',
       'FD_ALTAEMPLEADO', 'FI_DATOS_CORRECTOS', 'FI_OFERTA', 'FC_STATUS_EMP',
       'FI_STATUS_EMP', 'FC_NOMBRE_EMPLEADO', 'FC_APELLIDO_PATERNO',
       'FC_APELLIDO_MATERNO', 'FI_ID_PAIS_y', 'FD_FECHA_ALTA',
       'FNPAISNACIMIENTO', 'FNEDONACIMIENTO', 'FNESTADOCIVIL', 'FNESCOLARIDAD',
       'FNSEXO', 'FNNACIONALIDAD'],
      dtype='object')

In [32]:
m_demograficos.rename(columns={'FI_ID_PAIS_y':'FI_ID_PAIS'}, inplace=True)

/Users/ilucash/Documents/Proyectos/BIG/NAC/venv/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [33]:
m_demograficos

,#FI_ID_INSTITUCION,FI_EMPLEADO,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FC_INSTITUCION,FC_NOMBRECOMPLETO,FD_FECHANACIMIENTO,FC_PAISNACIMIENTO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
25722,4673,254435,1,1,8765,71946,IMSS PENSIONADOS,MARIA MONCERRATO GARCIA LOPEZ,10/27/1938 00:00:00,MEXICO,...,GARCIA,LOPEZ,1,03/28/2018 00:00:00,1,28,5,7,1,484
182346,11879,2464687,1,1,4802,41971,CUTSPEI SIN CLASIFICAR,ANA VELIA DIAZ LEY,12/03/1970 00:00:00,NaN,...,DIAZ,LEY,1,12/06/2020 00:00:00,1,28,2,7,1,484
24235,4673,261468,1,1,3638,32139,IMSS PENSIONADOS,PROCORO DE LA CRUZ ISLENO,04/09/1944 00:00:00,MEXICO,...,DE LA CRUZ,ISLENO,1,03/28/2018 00:00:00,1,30,2,7,2,484
93552,4673,1530516,1,1,602,65685,IMSS PENSIONADOS,MARCOS RAMIREZ,12/25/1945 00:00:00,NaN,...,NaN,RAMIREZ,1,NaN,1,11,3,7,2,484
208417,4673,2684580,1,1,9740,4858,IMSS PENSIONADOS,BERNABE INFANTE MATA,12/06/1960 00:00:00,NaN,...,INFANTE,MATA,1,12/08/2020 00:00:00,1,24,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,1,1,2196,3343,IMSS PENSIONADOS,LUIS JAVIER DIAZ HERNANDEZ,04/08/1960 00:00:00,NaN,...,DIAZ,HERNANDEZ,1,NaN,1,20,3,7,2,484
86232,5383,1391944,1,1,5116,27596,BAZ PORTABILIDAD NOMINA,GUADALUPE CONCEPCION FISHER MELGAR,09/15/1965 00:00:00,NaN,...,FISHER,MELGAR,1,03/11/2020 16:58:21,1,3,0,7,1,484
171619,5383,2347521,1,9,3278,7175,BAZ PORTABILIDAD NOMINA,RICARDO ALONSO CARRILLO AMAYA,12/08/1991 00:00:00,NaN,...,CARRILLO,AMAYA,1,12/05/2020 00:00:00,1,31,1,7,2,484
32713,4673,311643,1,20,9259,5969,IMSS PENSIONADOS,RODOLFO MARTINEZ DOMINGUEZ,09/27/1936 12:00:00,NaN,...,MARTINEZ,DOMINGUEZ,1,10/18/2016 00:00:00,1,9,2,7,2,484
15933,4673,197140,1,1,2063,41524,IMSS PENSIONADOS,ELENA GARCIA VALDEZ,02/03/1942 00:00:00,MEXICO,...,GARCIA,VALDEZ,1,12/28/2011 00:00:00,1,15,1,7,1,484

In [35]:
m_dispersiones.columns

Index(['#FI_ID_INSTITUCION_x', 'FI_EMPLEADO', 'FC_CUENTA', 'FD_ULTIMADISPER',
       'FI_TOTALDISPER', 'FN_SALARIO', 'FC_PERIODICIDADPAGO',
       'FI_CAPACIDADPAGO', 'FC_PRODUCTO', 'FI_ID_PRODUCTO', 'FI_CREDITOSACTIV',
       'FIPERIODICIDADPAGO', 'FI_CTA_DIGITOS'],
      dtype='object')

In [36]:
m_dispersiones.rename(columns={'#FI_ID_INSTITUCION_x':'#FI_ID_INSTITUCION'}, inplace=True)

/Users/ilucash/Documents/Proyectos/BIG/NAC/venv/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [37]:
m_demograficos

,#FI_ID_INSTITUCION,FI_EMPLEADO,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FC_INSTITUCION,FC_NOMBRECOMPLETO,FD_FECHANACIMIENTO,FC_PAISNACIMIENTO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
25722,4673,254435,1,1,8765,71946,IMSS PENSIONADOS,MARIA MONCERRATO GARCIA LOPEZ,10/27/1938 00:00:00,MEXICO,...,GARCIA,LOPEZ,1,03/28/2018 00:00:00,1,28,5,7,1,484
182346,11879,2464687,1,1,4802,41971,CUTSPEI SIN CLASIFICAR,ANA VELIA DIAZ LEY,12/03/1970 00:00:00,NaN,...,DIAZ,LEY,1,12/06/2020 00:00:00,1,28,2,7,1,484
24235,4673,261468,1,1,3638,32139,IMSS PENSIONADOS,PROCORO DE LA CRUZ ISLENO,04/09/1944 00:00:00,MEXICO,...,DE LA CRUZ,ISLENO,1,03/28/2018 00:00:00,1,30,2,7,2,484
93552,4673,1530516,1,1,602,65685,IMSS PENSIONADOS,MARCOS RAMIREZ,12/25/1945 00:00:00,NaN,...,NaN,RAMIREZ,1,NaN,1,11,3,7,2,484
208417,4673,2684580,1,1,9740,4858,IMSS PENSIONADOS,BERNABE INFANTE MATA,12/06/1960 00:00:00,NaN,...,INFANTE,MATA,1,12/08/2020 00:00:00,1,24,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,1,1,2196,3343,IMSS PENSIONADOS,LUIS JAVIER DIAZ HERNANDEZ,04/08/1960 00:00:00,NaN,...,DIAZ,HERNANDEZ,1,NaN,1,20,3,7,2,484
86232,5383,1391944,1,1,5116,27596,BAZ PORTABILIDAD NOMINA,GUADALUPE CONCEPCION FISHER MELGAR,09/15/1965 00:00:00,NaN,...,FISHER,MELGAR,1,03/11/2020 16:58:21,1,3,0,7,1,484
171619,5383,2347521,1,9,3278,7175,BAZ PORTABILIDAD NOMINA,RICARDO ALONSO CARRILLO AMAYA,12/08/1991 00:00:00,NaN,...,CARRILLO,AMAYA,1,12/05/2020 00:00:00,1,31,1,7,2,484
32713,4673,311643,1,20,9259,5969,IMSS PENSIONADOS,RODOLFO MARTINEZ DOMINGUEZ,09/27/1936 12:00:00,NaN,...,MARTINEZ,DOMINGUEZ,1,10/18/2016 00:00:00,1,9,2,7,2,484
15933,4673,197140,1,1,2063,41524,IMSS PENSIONADOS,ELENA GARCIA VALDEZ,02/03/1942 00:00:00,MEXICO,...,GARCIA,VALDEZ,1,12/28/2011 00:00:00,1,15,1,7,1,484

In [38]:
m_domicilios.columns

Index(['#FI_ID_INSTITUCION_y', 'FI_EMPLEADO', 'FC_CALLEHOGAR',
       'FC_NUMEXTHOGAR', 'FC_NUMINTHOGAR', 'FC_COLONIAHOGAR',
       'FC_MUNICIPIOHOGAR', 'FC_ESTADOHOGAR', 'FC_CODIGOPOSTAL', 'FC_PAIS',
       'FI_ID_TIPOVIVIENDA', 'FC_ID_TIPOVIVIENDA', 'FC_LATITUD', 'FC_LONGITUD',
       'FC_SUCURSAL', 'FI_ID_COLONIA', 'FI_ID_MUNICIPIO', 'FC_ID_ESTADO',
       'FI_ID_PAIS_x'],
      dtype='object')

In [39]:
m_domicilios.rename(columns={'#FI_ID_INSTITUCION_y':'#FI_ID_INSTITUCION','FI_ID_PAIS_x':'FI_ID_PAIS'}, inplace=True)

/Users/ilucash/Documents/Proyectos/BIG/NAC/venv/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [40]:
m_domicilios

,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_CALLEHOGAR,FC_NUMEXTHOGAR,FC_NUMINTHOGAR,FC_COLONIAHOGAR,FC_MUNICIPIOHOGAR,FC_ESTADOHOGAR,FC_CODIGOPOSTAL,FC_PAIS,FI_ID_TIPOVIVIENDA,FC_ID_TIPOVIVIENDA,FC_LATITUD,FC_LONGITUD,FC_SUCURSAL,FI_ID_COLONIA,FI_ID_MUNICIPIO,FC_ID_ESTADO,FI_ID_PAIS
25722,4673,254435,PROFESOR ROMERO,94,94,BUENAVISTA,MATAMOROS,TAMAULIPAS,87350,MEXICO,3,PROPIA,25.8656260000000000,-97.5178210000000000,NaN,1,22,28,1
182346,11879,2464687,C SN NOMBRE,SN,NaN,EJIDO EL OLIVO,VICTORIA,TAMAULIPAS,87000,MEXICO,3,PROPIA,23.7303730000000000,-99.1479870000000000,NaN,59,41,28,1
24235,4673,261468,RAFAEL SUAREZ R,SN,SN,GUADALUPE VICTORIA,POZA RICA DE HIDALGO,VERACRUZ,93290,MEXICO,3,PROPIA,20.5200440000000000,-97.4249770000000000,NaN,1,131,30,1
93552,4673,1530516,ARCE,112,NaN,Las Arboledas,León,GUANAJUATO,37480,MEXICO,3,PROPIA,21.1030560000000000,-101.6649800000000000,NaN,3,20,11,1
208417,4673,2684580,C REFORMA AGRARIA,2153,NaN,GENOVEVO RIVAS GILLEN,SOLEDAD DE GRACIANO SANCHEZ,SAN LUIS POTOSI,78437,Mexico,3,PROPIA,22.1574780000000000,-100.9239080000000000,NaN,14,35,24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,PRIV 1RA DE LA NORIA,105,NaN,OAXACA CENTRO,Oaxaca de Juárez,OAXACA,68000,MEXICO,3,PROPIA,17.0556610000000000,-96.7215940000000000,NaN,1,67,20,1
86232,5383,1391944,SAN PEDRO,SN,NaN,San Pedro,La Paz,BAJA CALIFORNIA SUR,23240,MEXICO,3,PROPIA,23.9413780000000000,-110.2722820000000000,NaN,1,3,3,1
171619,5383,2347521,C 40 X 27 Y 29,SN,SN,TZUCACAB,OXKUTZCAB,YUCATAN,97960,Mexico,3,PROPIA,20.0729550000000000,-89.0484910000000000,NaN,1,98,31,1
32713,4673,311643,AVENIDA 521,233,NaN,U H. SAN JUAN DE ARAGON,GUSTAVO A. MADERO,DISTRITO FEDERAL,07920,MEXICO,3,PROPIA,19.4735680000000000,-99.0867350000000000,NaN,3,7,9,1
15933,4673,197140,AMADOR SALAZAR,MZ 47,LT 5,LA ESPERANZA,ECATEPEC DE MORELOS,ESTADO DE MEXICO,55050,MEXICO,3,PROPIA,19.6008570000000000,-99.0170590000000000,NaN,9,33,15,1

In [41]:
m_demograficos

,#FI_ID_INSTITUCION,FI_EMPLEADO,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FC_INSTITUCION,FC_NOMBRECOMPLETO,FD_FECHANACIMIENTO,FC_PAISNACIMIENTO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
25722,4673,254435,1,1,8765,71946,IMSS PENSIONADOS,MARIA MONCERRATO GARCIA LOPEZ,10/27/1938 00:00:00,MEXICO,...,GARCIA,LOPEZ,1,03/28/2018 00:00:00,1,28,5,7,1,484
182346,11879,2464687,1,1,4802,41971,CUTSPEI SIN CLASIFICAR,ANA VELIA DIAZ LEY,12/03/1970 00:00:00,NaN,...,DIAZ,LEY,1,12/06/2020 00:00:00,1,28,2,7,1,484
24235,4673,261468,1,1,3638,32139,IMSS PENSIONADOS,PROCORO DE LA CRUZ ISLENO,04/09/1944 00:00:00,MEXICO,...,DE LA CRUZ,ISLENO,1,03/28/2018 00:00:00,1,30,2,7,2,484
93552,4673,1530516,1,1,602,65685,IMSS PENSIONADOS,MARCOS RAMIREZ,12/25/1945 00:00:00,NaN,...,NaN,RAMIREZ,1,NaN,1,11,3,7,2,484
208417,4673,2684580,1,1,9740,4858,IMSS PENSIONADOS,BERNABE INFANTE MATA,12/06/1960 00:00:00,NaN,...,INFANTE,MATA,1,12/08/2020 00:00:00,1,24,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,1,1,2196,3343,IMSS PENSIONADOS,LUIS JAVIER DIAZ HERNANDEZ,04/08/1960 00:00:00,NaN,...,DIAZ,HERNANDEZ,1,NaN,1,20,3,7,2,484
86232,5383,1391944,1,1,5116,27596,BAZ PORTABILIDAD NOMINA,GUADALUPE CONCEPCION FISHER MELGAR,09/15/1965 00:00:00,NaN,...,FISHER,MELGAR,1,03/11/2020 16:58:21,1,3,0,7,1,484
171619,5383,2347521,1,9,3278,7175,BAZ PORTABILIDAD NOMINA,RICARDO ALONSO CARRILLO AMAYA,12/08/1991 00:00:00,NaN,...,CARRILLO,AMAYA,1,12/05/2020 00:00:00,1,31,1,7,2,484
32713,4673,311643,1,20,9259,5969,IMSS PENSIONADOS,RODOLFO MARTINEZ DOMINGUEZ,09/27/1936 12:00:00,NaN,...,MARTINEZ,DOMINGUEZ,1,10/18/2016 00:00:00,1,9,2,7,2,484
15933,4673,197140,1,1,2063,41524,IMSS PENSIONADOS,ELENA GARCIA VALDEZ,02/03/1942 00:00:00,MEXICO,...,GARCIA,VALDEZ,1,12/28/2011 00:00:00,1,15,1,7,1,484

In [42]:
m_dispersiones

,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_CUENTA,FD_ULTIMADISPER,FI_TOTALDISPER,FN_SALARIO,FC_PERIODICIDADPAGO,FI_CAPACIDADPAGO,FC_PRODUCTO,FI_ID_PRODUCTO,FI_CREDITOSACTIV,FIPERIODICIDADPAGO,FI_CTA_DIGITOS
25722,4673,254435,01278765750107254356,11/30/2021 00:00:00,7,2795.84,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,107254356
182346,11879,2464687,01274802600120925148,12/09/2021 00:00:00,18,4851.71,SEMANAL,NaN,NOMINA AZTECA,10,0,1,120925148
24235,4673,261468,01278684360181466578,11/30/2021 00:00:00,7,3224.77,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,181466578
93552,4673,1530516,01270602181342037346,11/30/2021 00:00:00,7,4724.67,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,1,3,1342037346
208417,4673,2684580,01279740110141696900,11/30/2021 00:00:00,5,15370.32,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,141696900
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,01272196061318642100,11/30/2021 00:00:00,7,32709.01,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,1318642100
86232,5383,1391944,01275116860132501362,11/30/2021 00:00:00,8,5652.40,MENSUAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,0,3,132501362
171619,5383,2347521,01273278040152027698,11/16/2021 00:00:00,6,4310.00,MENSUAL,NaN,CREDITO DE PORTABILIDAD INMEDIATO,4,0,3,152027698
32713,4673,311643,01272080250173879726,11/30/2021 00:00:00,7,3054.92,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,173879726
15933,4673,197140,01272063110197317386,11/30/2021 00:00:00,7,2945.11,MENSUAL,NaN,PENSIONADOS Y JUBILADOS,11,0,3,197317386

In [43]:
m_domicilios

,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_CALLEHOGAR,FC_NUMEXTHOGAR,FC_NUMINTHOGAR,FC_COLONIAHOGAR,FC_MUNICIPIOHOGAR,FC_ESTADOHOGAR,FC_CODIGOPOSTAL,FC_PAIS,FI_ID_TIPOVIVIENDA,FC_ID_TIPOVIVIENDA,FC_LATITUD,FC_LONGITUD,FC_SUCURSAL,FI_ID_COLONIA,FI_ID_MUNICIPIO,FC_ID_ESTADO,FI_ID_PAIS
25722,4673,254435,PROFESOR ROMERO,94,94,BUENAVISTA,MATAMOROS,TAMAULIPAS,87350,MEXICO,3,PROPIA,25.8656260000000000,-97.5178210000000000,NaN,1,22,28,1
182346,11879,2464687,C SN NOMBRE,SN,NaN,EJIDO EL OLIVO,VICTORIA,TAMAULIPAS,87000,MEXICO,3,PROPIA,23.7303730000000000,-99.1479870000000000,NaN,59,41,28,1
24235,4673,261468,RAFAEL SUAREZ R,SN,SN,GUADALUPE VICTORIA,POZA RICA DE HIDALGO,VERACRUZ,93290,MEXICO,3,PROPIA,20.5200440000000000,-97.4249770000000000,NaN,1,131,30,1
93552,4673,1530516,ARCE,112,NaN,Las Arboledas,León,GUANAJUATO,37480,MEXICO,3,PROPIA,21.1030560000000000,-101.6649800000000000,NaN,3,20,11,1
208417,4673,2684580,C REFORMA AGRARIA,2153,NaN,GENOVEVO RIVAS GILLEN,SOLEDAD DE GRACIANO SANCHEZ,SAN LUIS POTOSI,78437,Mexico,3,PROPIA,22.1574780000000000,-100.9239080000000000,NaN,14,35,24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104382,4673,1640908,PRIV 1RA DE LA NORIA,105,NaN,OAXACA CENTRO,Oaxaca de Juárez,OAXACA,68000,MEXICO,3,PROPIA,17.0556610000000000,-96.7215940000000000,NaN,1,67,20,1
86232,5383,1391944,SAN PEDRO,SN,NaN,San Pedro,La Paz,BAJA CALIFORNIA SUR,23240,MEXICO,3,PROPIA,23.9413780000000000,-110.2722820000000000,NaN,1,3,3,1
171619,5383,2347521,C 40 X 27 Y 29,SN,SN,TZUCACAB,OXKUTZCAB,YUCATAN,97960,Mexico,3,PROPIA,20.0729550000000000,-89.0484910000000000,NaN,1,98,31,1
32713,4673,311643,AVENIDA 521,233,NaN,U H. SAN JUAN DE ARAGON,GUSTAVO A. MADERO,DISTRITO FEDERAL,07920,MEXICO,3,PROPIA,19.4735680000000000,-99.0867350000000000,NaN,3,7,9,1
15933,4673,197140,AMADOR SALAZAR,MZ 47,LT 5,LA ESPERANZA,ECATEPEC DE MORELOS,ESTADO DE MEXICO,55050,MEXICO,3,PROPIA,19.6008570000000000,-99.0170590000000000,NaN,9,33,15,1

In [44]:
m_domicilios.to_csv('DM_DatosDomicilio.txt', sep='|', index=False)
m_dispersiones.to_csv('DM_DatosDispersion.txt', sep='|', index=False)
m_demograficos.to_csv('DM_DatosGenerales.txt', sep='|', index=False)

In [45]:
#FI_PAISCU	FI_CANALCU	FI_SUCURSALCU	FI_FOLIOCU
marca_big.rename(columns={'#FI_ID_PAIS_CU':'FI_PAISCU','FI_ID_SUCURSAL_CU':'FI_SUCURSALCU','FI_ID_CANAL_CU':'FI_CANALCU','FI_FOLIO_CU':'FI_FOLIOCU'}, inplace=True)

In [46]:
marca_big

,FI_PAISCU,FI_SUCURSALCU,FI_CANALCU,FI_FOLIOCU,FI_COD_IDENTIFICADOR,FI_MARCA
0,-9,-5644,1,3323,0,0
1,-1,172,20,24400,0,0
2,1,100,1,87,14,1
3,1,100,1,192,4,1
4,1,100,1,239,10,1
...,...,...,...,...,...,...
1866302,1,7566,1,65859,4,1
1866303,1,6023,1,86678,4,1
1866304,1,5667,1,27704,4,1
1866305,1,9376,1,2917,4,1
1866306,1,5572,39,25027,4,1

In [47]:
marca_big = marca_big[['FI_PAISCU','FI_CANALCU','FI_SUCURSALCU','FI_FOLIOCU','FI_COD_IDENTIFICADOR','FI_MARCA']]

In [48]:
marca_big

,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FI_COD_IDENTIFICADOR,FI_MARCA
0,-9,1,-5644,3323,0,0
1,-1,20,172,24400,0,0
2,1,1,100,87,14,1
3,1,1,100,192,4,1
4,1,1,100,239,10,1
...,...,...,...,...,...,...
1866302,1,1,7566,65859,4,1
1866303,1,1,6023,86678,4,1
1866304,1,1,5667,27704,4,1
1866305,1,1,9376,2917,4,1
1866306,1,39,5572,25027,4,1

In [49]:
marca_big.merge(m_demograficos, on=['FI_PAISCU','FI_CANALCU','FI_SUCURSALCU','FI_FOLIOCU'])

,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FI_COD_IDENTIFICADOR,FI_MARCA,#FI_ID_INSTITUCION,FI_EMPLEADO,FC_INSTITUCION,FC_NOMBRECOMPLETO,...,FC_APELLIDO_PATERNO,FC_APELLIDO_MATERNO,FI_ID_PAIS,FD_FECHA_ALTA,FNPAISNACIMIENTO,FNEDONACIMIENTO,FNESTADOCIVIL,FNESCOLARIDAD,FNSEXO,FNNACIONALIDAD
0,1,1,107,21953,11,1,4673,2009843,IMSS PENSIONADOS,RUBIET PALACIOS CABRERA,...,PALACIOS,CABRERA,1,NaN,1,9,2,7,1,484
1,1,1,107,22197,15,1,4673,2045275,IMSS PENSIONADOS,RODOLFO NORIA RODRIGUEZ,...,NORIA,RODRIGUEZ,1,NaN,1,15,2,7,2,484
2,1,1,107,23497,10,1,6673,866620,GOBIERNO DE LA CIUDAD DE MEXICO ALCALDIA DE AZ...,MARIA LUISA AGUAYO MORALES,...,AGUAYO,MORALES,1,08/01/1999 00:00:00,1,9,1,3,1,484
3,1,1,107,25223,4,1,5383,1875898,BAZ PORTABILIDAD NOMINA,MILDRET JOSEFINA AGUILAR GONZALEZ,...,AGUILAR,GONZALEZ,1,09/24/2020 00:00:00,1,21,1,7,1,484
4,1,1,107,33467,11,1,4673,704671,IMSS PENSIONADOS,CARLOS RAMIREZ ARROYO,...,RAMIREZ,ARROYO,1,NaN,1,15,2,7,2,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,1,5673,38883,4,1,5383,2742333,BAZ PORTABILIDAD NOMINA,JOSE MANUEL PEÑA CORDOBA,...,PEÑA,CORDOBA,1,08/27/2021 18:15:12,1,30,0,7,2,484
996,1,1,4614,11725,4,1,5383,2680757,BAZ PORTABILIDAD NOMINA,JUAN CARLOS CALIZ MARTINEZ,...,CALIZ,MARTINEZ,1,07/31/2021 16:42:33,1,15,1,7,2,484
997,1,1,2164,53381,4,1,5383,2718180,BAZ PORTABILIDAD NOMINA,ALFREDO SANTILLAN REYES,...,SANTILLAN,REYES,1,08/14/2021 13:41:24,1,15,0,7,2,484
998,1,1,2516,112089,4,1,5383,2743048,BAZ PORTABILIDAD NOMINA,MARCOS ARIEL SOLIS PECH,...,SOLIS,PECH,1,08/28/2021 16:05:37,1,4,0,7,2,484
999,1,1,7977,82251,4,1,5383,2718996,BAZ PORTABILIDAD NOMINA,JORDAN IMANOL POSADA MACEIRA,...,POSADA,MACEIRA,1,08/15/2021 18:09:02,1,5,0,7,2,484

In [50]:
m_marca_big = marca_big.merge(m_demograficos, on=['FI_PAISCU','FI_CANALCU','FI_SUCURSALCU','FI_FOLIOCU'])

In [51]:
m_marca_big = m_marca_big[['FI_PAISCU','FI_CANALCU','FI_SUCURSALCU','FI_FOLIOCU','FI_COD_IDENTIFICADOR','FI_MARCA']]

In [52]:
m_marca_big

,FI_PAISCU,FI_CANALCU,FI_SUCURSALCU,FI_FOLIOCU,FI_COD_IDENTIFICADOR,FI_MARCA
0,1,1,107,21953,11,1
1,1,1,107,22197,15,1
2,1,1,107,23497,10,1
3,1,1,107,25223,4,1
4,1,1,107,33467,11,1
...,...,...,...,...,...,...
995,1,1,5673,38883,4,1
996,1,1,4614,11725,4,1
997,1,1,2164,53381,4,1
998,1,1,2516,112089,4,1
999,1,1,7977,82251,4,1

In [53]:
m_marca_big.to_csv('Marca_BIG.txt', sep='|', index=False)